#!/usr/bin/env bash
# Note: This file relies on variables and functions defined in the main script.

configure_arch_timers() {
    grep -qE "ID=arch|ID_LIKE=arch" /etc/os-release || return 0
    
    run "Starting paccache.timer" sudo systemctl enable --now paccache.timer
    run "Starting aur-trim.timer" systemctl --user enable --now aur-trim.timer
}

configure_ext4_services() {
    [[ ! -x /usr/sbin/e4defrag ]] && { error "e2fsprogs missing"; return 1; }
    lsblk -no FSTYPE | grep -q "ext4" || return 0

    run "Starting fstrim.timer" sudo systemctl enable --now fstrim.timer
}

configure_hyprland_services() {
    [[ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]] && return 0

    header "Hyprland Specific"
    local services=(
        hypridle.service 
        hyprpaper.service 
        pyprland.service 
        hyprpolkitagent.service 
        waybar.service 
        hyprsunset.service
    )

    for srv in "${services[@]}"; do
        run "Starting $srv" systemctl --user enable --now "$srv"
    done
}
