#!/usr/bin/env bash
# Note: This file relies on variables and functions defined in the main script.

# Colors for logging
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly RED='\033[0;31m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

# Helper Functions
header()  { printf "\n${BLUE}==== %s ====${NC}\n" "$1"; }
log()     { printf "${GREEN}[INFO]${NC} %s\n" "$1"; }
warn()    { printf "${YELLOW}[WARN]${NC} %s\n" "$1"; }
error()   { printf "${RED}[ERROR]${NC} %s\n" "$1"; }
success() { printf "${GREEN}[SUCCESS]${NC} %s\n" "$1"; }

log_task() { printf "${GREEN}[INFO]${NC} %s... " "$1"; }
ok()   { printf "${GREEN}%s${NC}\n" "Done."; }
fail() { printf "${RED}%s${NC}\n" "Failed."; }

# HELPER FUNCTIONS
run() {
    log_task "$1"
    shift
    
    local err_log
    err_log=$(mktemp)

    if "$@" 2>"$err_log" >/dev/null; then
        ok
    else
        fail
        [[ -s "$err_log" ]] && error "$(cat "$err_log")"
    fi
    rm -f "$err_log"
}

run_user_service(){
    run "$1" systemctl --user enable --now "$2"
}

run_system_service() {
    run "$1" sudo systemctl enable --now "$2"
}

manage() {
    local srv=$1 scope=$2 desc=$3
    read -p "$(echo -e "  ${YELLOW}??${NC} Enable $desc ($srv)? [y/N]: ")" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if [[ -z "$scope" ]]; then
            sudo systemctl enable --now "$srv"
        else
            systemctl "$scope" enable --now "$srv"
        fi
        success "$srv started"
    fi
}
