#!/usr/bin/env bash

# Source functions
FUNCTIONS_DIR="$HOME/.local/lib"
if [[ -d "$FUNCTIONS_DIR" ]]; then
    # shellcheck source=/dev/null
    for file in "$FUNCTIONS_DIR"/*; do
        if [[ -f $file ]]; then
            source "$file"
        fi
    done
else 
    echo "Could not import functions from $FUNCTIONS_DIR"
    exit 1
fi

# Ask for sudo privledges upfront
sudo -v 

# Package list
readonly PACMAN_PKGS=(
    scx-scheds
    scx-tools
)

# Package Management
log "Checking dependencies..."
sudo pacman -S --noconfirm --needed "${PACMAN_PKGS[@]}"

# Service management
if ! pgrep -x "scx_loader" > /dev/null; then
     systemctl enable --now sxc_loader
fi

# Scheduler Management
log "Switching to scx_cake gaming profile..."
if scxctl start --sched cake --profile gaming; then
    success "Enabled scx_cake."
else
    error "Could not enable/start scx_cake"
fi
