#!/usr/bin/env sh

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

log()   { printf "${GREEN}[INFO]${NC} %s\n" "$1"; }
error() { printf "${RED}[ERROR]${NC} %s\n" "$1"; }

STATE_FILE="/tmp/snapper-num"

# Capture the package list from Pacman
FULL_PKGS=$(cat)

# Allows the use of $1, $2, and $# (the count)
set -- $FULL_PKGS
COUNT=$#

# Now $COUNT and $1-$5 contain data
if [ "$COUNT" -gt 5 ]; then
    DESC_PKGS="$1 $2 $3 $4 $5... ($COUNT pkgs)"
else
    DESC_PKGS="$FULL_PKGS"
fi

# If no pre-snapshot state exists, just stop
[ ! -f "$STATE_FILE" ] && exit 0

PRE=$(cat "$STATE_FILE")

# Create the post-snapshot
if POST=$(snapper create -t post --pre-number "$PRE" -c number -d "Packages: $DESC_PKGS" -p); then
    log "Snapshot created: $PRE -> $POST"
    rm "$STATE_FILE"
else
    error "Failed to create post-snapshot" >&2
fi
