#!/usr/bin/env bash

# ==============================================================================
# USAGE: 
#   run_task "Description of task" <command>
#
# EXAMPLE:
#   run_task "Updating system" sudo pacman -Syu
#   run_task "Cleaning temp" rm -rf ./tmp
# ==============================================================================

# Task runner
run_task() {
    log_task "$1"
    shift
    
    local err_log
    err_log=$(mktemp)

    if "$@" 2>"$err_log" >/dev/null; then
        ok
    else
        fail
        [[ -s "$err_log" ]] && error "$(cat "$err_log")"
    fi
    rm -f "$err_log"
}
