#!/usr/bin/env bash

# =================================================================
# GLOBAL LINUX GAMING TWEAKS
# =================================================================

# --- Nvidia specific ---
if [[ -d /proc/driver/nvidia ]]; then
    export PROTON_DLSS_UPGRADE=1                                      # Allow swapping DLSS versions
    export PROTON_ENABLE_NVAPI=1                                      # Enable Nvidia features in games
    export __GL_SHADER_DISK_CACHE=1                                   # Enable shader cache
    export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1                      # Prevent shader files from being cleaned
    export __GL_SHADER_DISK_CACHE_SIZE=$((30 * 1024 * 1024 * 1024))   # Shader cache size
fi

# --- Gameplay capture ---
if command -v obs-vkcapture &> /dev/null; then
    export OBS_VKCAPTURE=1
fi

# --- Performance monitoring ---
if command -v mangohud &> /dev/null; then
    export MANGOHUD_CONFIGFILE="$HOME/dotfiles/mangohud/.config/MangoHud/MangoHud.conf"
    export MANGOHUD=1
fi

# --- Kernel Detection & Wrapper Selection ---
if grep -qi "cachyos" /proc/version; then
    if command -v game-performance &> /dev/null; then
        if command -v powerprofilesctl &> /dev/null; then
            command="game-performance $command"
        fi
    fi
else
    if command -v gamemoderun &> /dev/null; then
        command="gamemoderun $command"
    fi
fi

# --- Core Proton & Game Logic ---
export PROTON_USE_NTSYNC=1          # Faster kernel-level syncing
export PROTON_LOCAL_SHADER_CACHE=1  # Game-specific shader storage
export DXVK_HDR=1                   # Enable HDR Support

# --- Gamescope options ---
export SCB_NOSCOPE=1   # Keep OFF globally

# Gamescope function
activate_gamescope() {
    export SCB_NOSCOPE=0
    export ENABLE_GAMESCOPE_WSI=1
    export PROTON_ENABLE_HDR=1

    SCB_GAMESCOPE_ARGS="-f -w 2560 -h 1440 -W 2560 -H 1440 -r 240"
    SCB_GAMESCOPE_ARGS+=" --immediate-flips --force-grab-cursor --grab --rt"
    SCB_GAMESCOPE_ARGS+=" --hdr-enabled --hdr-itm-enabled"
    SCB_GAMESCOPE_ARGS+=" --hdr-sdr-content-nits 100 --hdr-itm-target-nits 400 --sdr-gamut-wideness 1"
}

# command+=""






# DEBUG
# export SCB_DEBUG=1
