#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e
set -o pipefail

# Colors for logging
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

# Helper Functions
header() { echo -e "\n${BLUE}==== $1 ====${NC}"; }
log() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }

log_task() { echo -ne "${GREEN}[INFO]${NC} $1... "; }
ok() { echo -e "${GREEN}Done.${NC}"; }
fail() { echo -e "${RED}Failed.${NC}"; }

# Stow Packages
STOW_FOLDERS=(
    backgrounds kwalletrc fastfetch wayland-pipewire-idle-inhibit hypr kitty
    mpv nvim starship swaync waybar wofi yazi zsh tmux uwsm systemd-user scopebuddy
    mangohud
)

# Dotfiles
DOTFILES_DIR="$HOME/dotfiles"
header "DOTFILE CONFIGURATION"

if [ -d "$DOTFILES_DIR" ]; then
    log "Stowing dotfiles..."
    cd "$DOTFILES_DIR"

    if [ -d "scripts/user-scripts" ]; then
        log_task "Stowing user scripts"
        if stow -d "scripts" -t "$HOME" --restow user-scripts; then ok; else fail; fi
    fi

    for folder in "${STOW_FOLDERS[@]}"; do
        if [ -d "$folder" ]; then
            log_task "Stowing $folder"
            if stow -t "$HOME" --restow "$folder"; then ok; else fail; fi
        else
            warn "Skipping $folder (not found)."
        fi
    done
    cd - >/dev/null

    # Sync system-level files
    SCRIPTS_SRC="$DOTFILES_DIR/scripts/system-scripts/usr/local/bin"
    CONFIGS_SRC="$DOTFILES_DIR/system-files"

    # SYSTEMD_SYSTEM="/etc/systemd/system"

    # Format: "source|target|mode"
    FILES_TO_SYNC=(
        "$SCRIPTS_SRC/reboot-to-windows|/usr/local/bin/reboot-to-windows|755"
        "$SCRIPTS_SRC/check-units|/usr/local/bin/check-units|755"
        "$SCRIPTS_SRC/check-orphans|/usr/local/bin/check-orphans|644"

        "$CONFIGS_SRC/root|/etc/snapper/configs/root|644"
        "$CONFIGS_SRC/snap-pac.ini|/etc/snap-pac.ini|644"
        "$CONFIGS_SRC/orphan-check.hook|/etc/pacman.d/hooks/orphan-check.hook|755"

    )
    
    for entry in "${FILES_TO_SYNC[@]}"; do
        IFS='|' read -r src target mode <<<"$entry"

        if [ -f "$src" ]; then
            mode=${mode:-644}

            log_task "Syncing $target (mode: $mode)"
            if sudo install -Dm "$mode" "$src" "$target"; then
                ok
            else
                fail
            fi
        else
            warn "Source file missing: $src"
        fi
    done

fi


