#!/usr/bin/env bash

# Set variables
sys_failed=$(systemctl --failed --no-legend)
user_failed=$(systemctl --user --failed --no-legend 2>/dev/null)

# Detect failed services
msg=()
[[ -n "$sys_failed" ]] && msg+=("[System Units]" "$sys_failed" "")
[[ -n "$user_failed" ]] && msg+=("[User Units]" "$user_failed")

# Notify user
if [[ ${#msg[@]} -gt 0 ]]; then
    notify-send -u critical "⚠️ Systemd Failure" "$(printf '%s\n' "${msg[@]}")"
else
    notify-send -u low -t 3000 "✅ System Healthy" "All units are running correctly."
fi
