# ~/.config/mpd/mpd.conf

music_directory    "~/Music"
playlist_directory "~/Music/playlists"
db_file            "~/.local/share/mpd/database""

auto_update "yes"
bind_to_address "/tmp/mpd_socket"

audio_output {
    type    "pipewire"
    name    "PipeWire"
}
