#!/usr/bin/env bash

## Source functions
FUNCTIONS_DIR="$HOME/dotfiles/scripts/external-scripts/setup-script/.setup/functions"
LIBS=("services-systemd-functions" "environment-specific-services")

if [[ -d "$FUNCTIONS_DIR" ]]; then
    # shellcheck source=/dev/null
    for lib in "${LIBS[@]}"; do
        source "$FUNCTIONS_DIR/$lib"
    done
else
    error "Could not import functions from $FUNCTIONS_DIR"
    exit 1
fi

#  Initialization
log "Verifying sudo access..."
sudo -v

log_task "Reloading systemd daemons"
sudo systemctl daemon-reload
systemctl --user daemon-reload
ok

# System Services
header "System Services"

manage "NetworkManager.service"         ""  "Network Management"
manage "bluetooth.service"              ""  "Bluetooth"
manage "power-profiles-daemon.service"  ""  "Power Management"
manage "sshd.service"                   ""  "SSH Daemon"

# Environment specific services
header "Environment Setup"

configure_arch_timers
configure_ext4_services
configure_hyprland_services

# User Services
header "User services"
run "Starting idle inhibitor" systemctl --user enable --now wayland-pipewire-idle-inhibit.service
run "Starting failed unit checker" systemctl --user enable --now failed-units-check.timer
