# --- General ---
profile=high-quality
vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
hwdec=auto-safe
# fullscreen=yes

# --- Color Management & 10-bit ---
dither-depth=auto 
dither=fruit

# --- Profile for HDR Content ---
[HDR_Playback]
profile-cond=p["video-params/primaries"] == "bt.2020"
profile-restore=copy
target-colorspace-hint=yes
target-contrast=inf
tone-mapping=bt.2446a 
target-peak=400

# --- Profile for SDR Content ---
[SDR_Playback]
profile-cond=p["video-params/sig-peak"] <= 1
target-colorspace-hint=no
deband=yes
