# --- General ---
profile=high-quality
vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
hwdec=auto-safe

# --- Color Management & Dithering ---
dither-depth=auto 
dither=fruit

# --- Dynamic HDR Passthrough ---
target-colorspace-hint=auto
target-colorspace-hint-mode=source-dynamic
