# --- General ---
profile=high-quality
vo=gpu-next
hwdec=auto

# --- OLED Optimization ---
[OLED-Optimization]
profile-cond=p["video-params/gamma"] == "pq" or p["video-params/gamma"] == "hlg"
target-contrast=inf
