# No performance metrics
[preset 1]
no_display

# Minimal & Clean
[preset 2]
legacy_layout=0
horizontal
font_size=18
hud_no_margin
fps
fps_color_change
fps_metrics=avg,0.01,0.001
frametime
frame_timing=15
cpu_stats
cpu_temp
gpu_stats
gpu_temp
vram
ram

# Balanced & Useful
[preset 3]
font_size=20
ram
fps_metrics=avg,0.01,0.001
gpu_status
gpu_temp
vram
cpu_stats
cpu_temp
frametime
frame_timing_detailed=15

# Highly detailed
[preset 4]
font_size=20
gpu_status
gpu_temp
cpu_status
cpu_temp
vram
ram
core_load
core_load_change
fps_metrics=avg,0.01,0.001
frametime
frame_timing_detailed

# Gamescope specific (Experimental)
debug
fsr
hdr
wine
refresh_rate
throttling_status
throttling_status_graph
