#!/usr/bin/env bash

set -e
set -o pipefail

echo "--- Detecting System Capabilities ---"
/lib/ld-linux-x86-64.so.2 --help | grep "supported"

echo "--- Downloading CachyOS Repo Helper ---"
WORKDIR=$(mktemp -d)
cd "$WORKDIR"

curl -L https://mirror.cachyos.org/cachyos-repo.tar.xz -o cachyos-repo.tar.xz

echo "--- Extracting and Installing ---"
tar xvf cachyos-repo.tar.xz
cd cachyos-repo

sudo -v
sudo ./cachyos-repo.sh

echo "--- Cleaning up ---"
rm -rf "$WORKDIR"

# Sync repos
sudo pacman -Syu --needed --noconfirm 

# CachyOS kernel
PACMAN_PACKAGES=()

# Prompt to install the cachy kernel
read -r -p "$(echo -e "  ${YELLOW}??${NC} Install CachyOS kernel? (y/N): ")" install_cachy_kernel
if [[ "$install_cachy_kernel" =~ ^[Yy]$ ]]; then 
    PACMAN_PACKAGES+=("linux-cachyos" "linux-cachyos-headers")
fi

echo "Installing Official Packages..."
sudo pacman -S --needed --noconfirm "${PACMAN_PACKAGES[@]}"

# Prompt to remove the generic kernel
read -r -p "$(echo -e "  ${YELLOW}??${NC} Remove Generic kernel? (y/N): ")" remove_generic_kernel
if [[ "$remove_generic_kernel" =~ ^[Yy]$ ]]; then 
    sudo pacman -Rns --noconfirm linux linux-headers
fi
