#!/usr/bin/env bash

# Ask for sudo privledges upfront
sudo -v

# Package list
PACMAN_PKGS=(scx-scheds scx-tools)
MISSING_PACKAGES=()

# Check if packages exist on system
for pkg in "${PACMAN_PKGS[@]}"; do
    if ! pacman -Qq "$pkg" &>/dev/null; then
        MISSING_PACKAGES+=("$pkg")
    fi
done

# Install any missing packages
if ! [[ ${#MISSING_PACKAGES[@]} -eq 0 ]]; then
    echo "Installing missing packages: ${MISSING_PACKAGES[*]}"
    sudo pacman -S --needed --noconfirm "${MISSING_PACKAGES[@]}"
fi

# Service management
if ! pgrep -x "scx_loader" >/dev/null; then
    systemctl enable --now sxc_loader
fi
