general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Dim screen
listener {
    timeout = 90
    on-timeout = ddcutil setvcp 10 30 --async
    on-resume = ddcutil setvcp 10 50 --async
}

# Lock session
listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

# Turn off screen
listener {
    timeout = 125
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && ddcutil setvcp 10 50 --async
}

# Suspend
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
