#!/usr/bin/env bash
# Note: This file relies on variables and functions defined in the main script.

# Colors for logging
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

# Helper Functions
header()  { echo -e "\n${BLUE}==== $1 ====${NC}"; }
log()     { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }

log_task() { echo -ne "${GREEN}[INFO]${NC} $1... "; }
ok()       { echo -e "${GREEN}Done.${NC}"; }
fail()     { echo -e "${RED}Failed.${NC}"; }

# HELPER FUNCTIONS
run() {
    log_task "$1"
    shift
    
    local err_log
    err_log=$(mktemp)

    if "$@" 2>"$err_log" >/dev/null; then
        ok
    else
        fail
        [[ -s "$err_log" ]] && error "$(cat "$err_log")"
    fi
    rm -f "$err_log"
}

run_user_service(){
    run "$1" systemctl --user enable --now "$2"
}

run_system_service() {
    run "$1" sudo systemctl enable --now "$2"
}

manage() {
    local srv=$1 scope=$2 desc=$3
    read -p "$(echo -e "  ${YELLOW}??${NC} Enable $desc ($srv)? [y/N]: ")" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if [[ -z "$scope" ]]; then
            sudo systemctl enable --now "$srv"
        else
            systemctl "$scope" enable --now "$srv"
        fi
        success "$srv started"
    fi
}
