#!/usr/bin/env bash
# Note: This file relies on variables and functions defined in the main script.

header "INSTALLATION PHASE"

# Update System
log_task "Updating system"
if sudo pacman -Syu --noconfirm; then
    ok
else
    fail
    error "System update failed. Check your internet connection or mirrors."
fi

# Install Rustup
if ! command -v rustup &>/dev/null; then
    log_task "Installing rustup"
    if sudo pacman -S --noconfirm rustup && 
       rustup default stable; then
        ok
    else
        fail
    fi
else
    log_task "Rustup already installed."
    ok
fi

# Install Paru
if ! command -v paru &>/dev/null; then
    log_task "Installing Paru"
    if sudo pacman -S --needed --noconfirm base-devel git &&
       git clone https://aur.archlinux.org/paru.git /tmp/paru &&
       (cd /tmp/paru && makepkg -si --noconfirm) &&
       rm -rf /tmp/paru; then
        ok
    else
        fail
    fi
else
    log_task "Paru already installed."
    ok
fi

# Install Official Packages
log_task "Installing Official Packages..."
sudo pacman -S --needed --noconfirm "${PACMAN_PACKAGES[@]}"
ok

# Install AUR Packages
log_task "Installing AUR Packages..."
paru -S --needed --noconfirm "${AUR_PACKAGES[@]}"
ok

# Install Flatpaks
log_task "Installing Flatpak Apps..."
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y --noninteractive --or-update flathub "${FLATPAK_APPS[@]}"
ok
