#!/usr/bin/env bash
# Note: This file relies on variables and functions defined in the main script.

configure_arch_timers() {
    # Check inside the function
    if ! grep -qE "ID=arch|ID_LIKE=arch" /etc/os-release; then
        return 0 # Exit quietly if not Arch
    fi

    log "Arch detected: Installing systemd units..."
    run_task "Enabling aur-trim.timer" "systemctl --user enable --now aur-trim.timer"
    
}

configure_hyprland_services() {
    local IS_HYPRLAND=false
    if [[ "${XDG_SESSION_DESKTOP:-}" == "Hyprland" || -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
        IS_HYPRLAND=true
        header "Configuring Hyprland-specific services"
    fi

    if $IS_HYPRLAND; then
        manage_service "hypridle.service"        "--user" "enable" "Idle daemon"          "Y"
        manage_service "hyprpaper.service"       "--user" "enable" "Wallpaper daemon"     "Y"
        manage_service "pyprland.service"        "--user" "enable" "Pyprland plugins"     "Y"
        manage_service "hyprpolkitagent.service" "--user" "enable" "Polkit Authentication" "Y"
        manage_service "waybar.service"          "--user" "enable" "Status bar"           "Y"
        manage_service "hyprsunset.service"      "--user" "enable" "Blue light filter"    "Y"
    else
        log "Not in Hyprland. Skipping Hyprland-specific services."
    fi
}
