[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.obsidian]
animation = "fromTop" 
command = "/usr/bin/obsidian"
class = "obsidian" 
size = "90% 90%"
lazy = false

[scratchpads.pavucontrol]
animation = "fromTop"
command = "/usr/bin/pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "90% 90%"
lazy = false
