#!/usr/bin/env bash

xdg_setup() {
    header "XDG DIRECTORY SETUP"

    # Base XDG Setup
    export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
    export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
    export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
    export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

    # Secure runtime
    export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

    # Application Redirects
    export CARGO_HOME="${CARGO_HOME:-$XDG_DATA_HOME/cargo}"
    export RUSTUP_HOME="${RUSTUP_HOME:-$XDG_DATA_HOME/rustup}"
    export GNUPGHOME="${GNUPGHOME:-$XDG_DATA_HOME/gnupg}"
    export PYTHONHISTORY="${PYTHONHISTORY:-$XDG_STATE_HOME/python/history}"
    export GOPATH="${GOPATH:-$XDG_DATA_HOME/go}"
    export DOTNET_CLI_HOME="$XDG_DATA_HOME/dotnet"
    export NUGET_PACKAGES="$XDG_DATA_HOME/nuget/packages"
    export PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"
    export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
    export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js"
    export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
    export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm"
    export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

    # Nvidia
    export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
    export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME/nv"

    # Android
    export ANDROID_USER_HOME="$XDG_DATA_HOME/android"

    # Create secure directories
    log_task "Initializing Secure Directories"
    [[ ! -d "$XDG_RUNTIME_DIR" ]] && install -d -m 700 "$XDG_RUNTIME_DIR"
    [[ ! -d "$GNUPGHOME" ]] && install -d -m 700 "$GNUPGHOME"

    # Create standard directories
    log_task "Creating Directory Structure"
    local target_dirs=(
        "$XDG_DATA_HOME"/{cargo,rustup,go,dotnet,nuget/packages,tmux/plugins,pki}
        "$XDG_CONFIG_HOME"/{zsh,parallel,npm/config,gtk-2.0,nvidia}
        "$XDG_CACHE_HOME"/{zsh,npm,nv}
        "$XDG_STATE_HOME"/{zsh,python}
    )

    if mkdir -p "${target_dirs[@]}"; then
        ok
    else
        fail
    fi

    # Sync with Systemd/D-Bus
    if command -v dbus-update-activation-environment >/dev/null; then
        dbus-update-activation-environment --all >/dev/null 2>&1
    fi
}
