#!/usr/bin/env bash

xdg_setup() {
    header "XDG DIRECTORY SETUP"

    # Ensures applications follow the XDG Base Directory Specification
    export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
    export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
    export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
    export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

    # --- APPLICATION REDIRECTS ---

    # Rust
    export CARGO_HOME="${CARGO_HOME:-$XDG_DATA_HOME/cargo}"
    export RUSTUP_HOME="${RUSTUP_HOME:-$XDG_DATA_HOME/rustup}"

    # Security & Languages
    export GNUPGHOME="${GNUPGHOME:-$XDG_DATA_HOME/gnupg}"
    export PYTHONHISTORY="${PYTHONHISTORY:-$XDG_STATE_HOME/python/history}"
    export GOPATH="${GOPATH:-$XDG_DATA_HOME/go}"

    # Development Frameworks
    export DOTNET_CLI_HOME="$XDG_DATA_HOME/dotnet"
    export NUGET_PACKAGES="$XDG_DATA_HOME/nuget/packages"
    export PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"
    export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

    # Theming
    export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

    # Cache
    export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"

    # Toolkit
    export QT_QPA_PLATFORMTHEME="qt6ct"
    export QT_QPA_PLATFORM="wayland;xcb"
    export ADW_DISABLE_PORTAL=1

    # Create directories if missing
    target_dirs=(
        "$XDG_DATA_HOME" "$XDG_CONFIG_HOME" "$XDG_STATE_HOME" "$XDG_CACHE_HOME"
        "$XDG_CONFIG_HOME/zsh"
        "$XDG_STATE_HOME/zsh"
        "$XDG_CACHE_HOME/zsh"
        "$XDG_CONFIG_HOME/gtk-2.0"
        "$XDG_STATE_HOME/python"
        "$XDG_CACHE_HOME/nv"
        "$GNUPGHOME"
        "$XDG_DATA_HOME/tmux/plugins"
        "$XDG_DATA_HOME/pki"
    )

    log_task "Creating directory structure"
    if mkdir -p "${target_dirs[@]}"; then
        ok
    else
        fail
    fi

    # Hardware Specifics
    if [[ -d "/sys/module/nvidia" ]]; then
        export LIBVA_DRIVER_NAME=nvidia         # Hardware Video Acceleration
        export __GLX_VENDOR_LIBRARY_NAME=nvidia # OpenGL Routing
        export GBM_BACKEND=nvidia-drm           # The Wayland Handshake

        # Explicitly enable G-Sync and VRR
        export __GL_GSYNC_ALLOWED=1
        export __GL_VRR_ALLOWED=1
    fi
}
