#!/usr/bin/env zsh

# ga: Stage files (defaults to all) and show status
ga() {
    git add "${@:-.}"
    git status
}

gm() {
    local source_branch="${1:-testing}"
    local target_branch="${2:-main}"

    local original_branch
    original_branch=$(git symbolic-ref --short HEAD 2>/dev/null)

    git pull --rebasee origin "$target_branch"
    git merge "$source_branch"
    git push "$target_branch"
    git switch "$original_branch"
}

git-reset-hard() {
    local branch="${1:-$(git remote show origin | awk '/HEAD branch/ {print $NF}' || echo "main")}"
    git reset --hard "origin/$branch"
}

gd() {
  if [[ -z "$1" ]]; then
    git diff HEAD
  else
    git diff "$@"
  fi
}
