#!/usr/bin/env zsh

# Extract any common compressed file types
extract() {
  if [[ $# -eq 0 ]]; then
    error "Please provide at least one file" >&2
    usage "extract <file1> <file2> ..."
    return 1
  fi

  # Iterate through every file passed to the function
  for file in "$@"; do
    if [[ -f "$file" ]]; then
      case "${file:l}" in
        *.tar.bz2|*.tbz2) tar xjf "$file"    ;;
        *.tar.gz|*.tgz)   tar xzf "$file"    ;;
        *.bz2)            bunzip2 "$file"    ;;
        *.rar)            unrar x "$file"    ;;
        *.gz)             gunzip "$file"     ;;
        *.tar)            tar xf "$file"     ;;
        *.zip)            unzip "$file"      ;;
        *.Z)              uncompress "$file" ;;
        *.7z)             7z x "$file"       ;;
        *)                error "'$file' cannot be extracted via extract()" >&2 ;;
      esac
    else
      error "'$file' is not a valid file" >&2
    fi
  done
}

# Open tldr manual in neovim
tldr() {
    if [[ -n "$1" ]]; then
        command tldr "$@" | nvim -R -c "set ft=help" -
    else
        error "Please provide a command" >&2
        usage "tldr <package>"
        return 1
    fi
}
