#!/usr/bin/env zsh

# zl: Navigate with 'z' and immediately list directory contents
zl() {
    if [[ -z "$@" ]]; then
        eza -1 --icons --git --group-directories-first --time-style=long-iso
    else
        z "$@" && \
        eza -1 --icons --git --group-directories-first --time-style=long-iso
    fi
}

# zlh: Navigate with 'z' and list ALL contents (including hidden)
zlh() {
    if [[ -z "$@" ]]; then
        eza -1A --icons --git --group-directories-first --time-style=long-iso
    else 
        z "$@" && \
        eza -1A --icons --git --group-directories-first --time-style=long-iso
    fi
}
