#!/usr/bin/env bash
# Note: This file relies on variables and functions defined in the main script.

header "INSTALLATION PHASE"

# Update System
log_task "Updating system"
if sudo pacman -Syu --noconfirm >/dev/null; then
    ok
else
    fail
    error "System update failed. Check your internet connection or mirrors."
    exit 1
fi

# Install Rustup
if ! command -v rustup >/dev/null; then
    log_task "Installing rustup"
    if sudo pacman -S --noconfirm rustup && 
       rustup default stable; then
        ok
    else
        fail
        exit 1
    fi
else
    log_task "Rustup already installed."
    ok
fi

# Install Paru
if ! command -v paru >/dev/null; then
    log_task "Installing Paru"
    if sudo pacman -S --needed --noconfirm base-devel git &&
       git clone https://aur.archlinux.org/paru.git /tmp/paru &&
       (cd /tmp/paru && makepkg -si --noconfirm) &&
       rm -rf /tmp/paru; then
        ok
    else
        fail
        rm -rf /tmp/paru
        exit 1
    fi
else
    log_task "Paru already installed."
    ok
fi

# Map missing packages
mapfile -t MISSING_PACKAGES < <(pacman -T "${PACMAN_PACKAGES[@]}")
mapfile -t MISSING_AUR < <(pacman -T "${AUR_PACKAGES[@]}")

mapfile -t MISSING_FLATPAKS < <(
    printf "%s\n" "${FLATPAK_APPS[@]}" | grep -vFxf <(flatpak list --app --columns=application)
)

# Install missing official pkgs
if [[ ${#MISSING_PACKAGES[@]} -gt 0 ]]; then
    log_task "Installing missing official packages"
    sudo pacman -S --needed --noconfirm "${MISSING_PACKAGES[@]}"
    ok
fi

# Install missing AUR pkgs
if [[ ${#MISSING_AUR[@]} -gt 0 ]]; then
    log_task "Installing missing AUR packages"
    sudo pacman -S --needed --noconfirm "${MISSING_AUR[@]}"
    ok
fi

# Install missing flatpaks
if [[ ${#MISSING_FLATPAKS[@]} -gt 0 ]]; then
    log_task "Installing or updating flatpaks"
    flatpak install -y --noninteractive --or-update flathub "${FLATPAK_APPS[@]}"
    ok
fi
