#!/usr/bin/env bash

# Colors for logging
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

# Helper Functions
header() { echo -e "\n${BLUE}==== $1 ====${NC}"; }
log() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_task() { echo -ne "${GREEN}[INFO]${NC} $1... "; }
ok() { echo -e "${GREEN}Done.${NC}"; }
fail() { echo -e "${RED}Failed.${NC}"; }

header "HARDWARE CONFIGURATION"

# Install chwd if avaliable
if ! command -v chwd >/dev/null; then
    if pacman -Sl | grep -q "chwd"; then
        log_task "Hardware detection available, installing chwd"
        sudo pacman -S --needed --noconfirm chwd
        ok
    else
        warn "chwd not found in repos. Skipping auto-detection."
    fi
fi

# Hardware Detection via chwd
if command -v chwd >/dev/null; then
    if sudo chwd -a >/dev/null; then
        log_task "Auto-detecting and installing drivers via chwd"
        ok
    else
        if lspci | grep -iq "nvidia"; then
            NVIDIA_PACKAGES=(nvidia-open-dkms)
        fi
    fi
fi

# NVIDIA Utilities & Configuration
if lspci | grep -iq "nvidia"; then
    NVIDIA_PACKAGES+=(nvidia-settings egl-wayland lib32-nvidia-utils libva-nvidia-driver)
    mapfile -t MISSING_PACKAGES < <(pacman -T "${NVIDIA_PACKAGES[@]}")

    # Install any missing packages
    if [[ ${#MISSING_PACKAGES[@]} -gt 0 ]]; then
        log_task "Installing missing packages: ${MISSING_PACKAGES[*]}"
        sudo pacman -S --needed --noconfirm "${MISSING_PACKAGES[@]}" >/dev/null
        ok
    fi

    GRUB_FILE="/etc/default/grub"
    PARAM="nvidia-drm.modeset=1 nvidia-drm.fbdev=1"

    if [[ -f "$GRUB_FILE" ]] && ! grep -q "nvidia-drm.modeset=1" "$GRUB_FILE"; then
        log_task "Adding KMS parameters to GRUB"
        sudo sed -i "s/\(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*\)\"/\1 $PARAM\"/" "$GRUB_FILE"
        sudo grub-mkconfig -o /boot/grub/grub.cfg
        touch /tmp/reboot_required
        ok
    fi
fi

# Cleanup mkinitcpio
if command -v dracut >/dev/null; then
    if pacman -Qq mkinitcpio &>/dev/null; then
        log_task "Removing mkinitcpio"
        sudo pacman -Rns --noconfirm mkinitcpio
        sudo grub-mkconfig -o /boot/grub/grub.cfg
        touch /tmp/reboot_required
        ok
    fi
fi

# Enable NVIDIA KMS if chwd doesnt exist
if ! command -v chwd >/dev/null; then
    CONF_FILE="/etc/modprobe.d/nvidia.conf"
    SETTING="options nvidia-drm modeset=1"

    if [[ ! -f "$CONF_FILE" ]] || ! grep -Fxq "$SETTING" "$CONF_FILE"; then
        log_task "Enabling NVIDIA Kernel Mode Setting (KMS)..."
        if echo "$SETTING" | sudo tee "$CONF_FILE" >/dev/null; then
            touch /tmp/reboot_required
            ok
        else
            fail
        fi
    else
        log_task "NVIDIA KMS already configured."
        ok
    fi
fi
