#!/usr/bin/env sh

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

log()  { printf "${GREEN}[INFO]${NC} %s\n" "$1"; }
error()   { printf "${RED}[ERROR]${NC} %s\n" "$1"; }

STATE_FILE="/tmp/snapper-num"

# If no pre-snapshot state exists, just stop
[ ! -f "$STATE_FILE" ] && exit 0

PRE=$(cat "$STATE_FILE")

# Create the post-snapshot silently
if POST=$(snapper create -t post --pre-number "$PRE" -c number -d "Pacman update" -p); then
    log "Snapshot created: $PRE -> $POST"
    rm "$STATE_FILE"
else
    error "Failed to create post-snapshot" >&2
fi
